/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait CurrencyExchangeRatesApi: Send + Sync {
    /// DELETE /v1/exchange-rates/{id}
    ///
    /// Delete a specific currency exchange rate by its internal ID.
    async fn delete_specific_currency_exchange_rate(
        &self,
        params: DeleteSpecificCurrencyExchangeRateParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRateError>>;

    /// DELETE /v1/exchange-rates/{from}/{to}/{date}
    ///
    /// Delete the currency exchange rate from 'from' to 'to' on the specified date.  It's important to know that the reverse exchange rate (from 'to' to 'from') will not be deleted and Firefly III will still be able to infer the correct exchange rate from the reverse one.
    async fn delete_specific_currency_exchange_rate_on_date(
        &self,
        params: DeleteSpecificCurrencyExchangeRateOnDateParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRateOnDateError>>;

    /// DELETE /v1/exchange-rates/{from}/{to}
    ///
    /// Deletes ALL currency exchange rates from 'from' to 'to'. It's important to know that the reverse exchange rates (from 'to' to 'from') will not be deleted and Firefly III will still be able to infer the correct exchange rate from the reverse one.
    async fn delete_specific_currency_exchange_rates(
        &self,
        params: DeleteSpecificCurrencyExchangeRatesParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRatesError>>;

    /// GET /v1/exchange-rates
    ///
    /// List exchange rates that Firefly III knows.
    async fn list_currency_exchange_rates(
        &self,
        params: ListCurrencyExchangeRatesParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListCurrencyExchangeRatesError>>;

    /// GET /v1/exchange-rates/{id}
    ///
    /// List a single specific exchange rate by its ID.
    async fn list_specific_currency_exchange_rate(
        &self,
        params: ListSpecificCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<ListSpecificCurrencyExchangeRateError>>;

    /// GET /v1/exchange-rates/{from}/{to}/{date}
    ///
    /// List the exchange rate for the from and to-currency on the requested date.
    async fn list_specific_currency_exchange_rate_on_date(
        &self,
        params: ListSpecificCurrencyExchangeRateOnDateParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListSpecificCurrencyExchangeRateOnDateError>>;

    /// GET /v1/exchange-rates/{from}/{to}
    ///
    /// List all exchange rates from/to the mentioned currencies.
    async fn list_specific_currency_exchange_rates(
        &self,
        params: ListSpecificCurrencyExchangeRatesParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListSpecificCurrencyExchangeRatesError>>;

    /// POST /v1/exchange-rates
    ///
    /// Stores a new exchange rate. The data required can be submitted as a JSON body or as a list of parameters.
    async fn store_currency_exchange_rate(
        &self,
        params: StoreCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<StoreCurrencyExchangeRateError>>;

    /// POST /v1/exchange-rates/by-date/{date}
    ///
    /// Stores a new set of exchange rates. The date is fixed (in the URL parameter) and the data required can be submitted as a JSON body.
    async fn store_currency_exchange_rates_by_date(
        &self,
        params: StoreCurrencyExchangeRatesByDateParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<StoreCurrencyExchangeRatesByDateError>>;

    /// POST /v1/exchange-rates/by-currencies/{from}/{to}
    ///
    /// Stores a new set of exchange rates for this pair. The date is variable, and the data required can be submitted as a JSON body.
    async fn store_currency_exchange_rates_by_pair(
        &self,
        params: StoreCurrencyExchangeRatesByPairParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<StoreCurrencyExchangeRatesByPairError>>;

    /// PUT /v1/exchange-rates/{id}
    ///
    /// Used to update a single currency exchange rate by its ID. Including the from/to currency is optional.
    async fn update_currency_exchange_rate(
        &self,
        params: UpdateCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<UpdateCurrencyExchangeRateError>>;

    /// PUT /v1/exchange-rates/{from}/{to}/{date}
    ///
    /// Used to update a single currency exchange rate by its currency codes and date
    async fn update_currency_exchange_rate_by_date(
        &self,
        params: UpdateCurrencyExchangeRateByDateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<UpdateCurrencyExchangeRateByDateError>>;
}

pub struct CurrencyExchangeRatesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl CurrencyExchangeRatesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rate`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSpecificCurrencyExchangeRateParams {
    /// The ID of the requested currency exchange rate.
    pub id: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rate_on_date`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSpecificCurrencyExchangeRateOnDateParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    pub date: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rates`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSpecificCurrencyExchangeRatesParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::list_currency_exchange_rates`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListCurrencyExchangeRatesParams {
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rate`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListSpecificCurrencyExchangeRateParams {
    /// The ID of the requested currency exchange rate.
    pub id: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rate_on_date`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListSpecificCurrencyExchangeRateOnDateParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    pub date: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rates`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListSpecificCurrencyExchangeRatesParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::store_currency_exchange_rate`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct StoreCurrencyExchangeRateParams {
    /// JSON array or key=value pairs with the necessary exchange rate information. See the model for the exact specifications.
    pub currency_exchange_rate_store: models::CurrencyExchangeRateStore,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::store_currency_exchange_rates_by_date`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct StoreCurrencyExchangeRatesByDateParams {
    pub date: String,
    /// JSON array with the necessary currency exchange rate information. See the model for the exact specifications.
    pub currency_exchange_rate_store_by_date: models::CurrencyExchangeRateStoreByDate,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::store_currency_exchange_rates_by_pair`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct StoreCurrencyExchangeRatesByPairParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    /// JSON array with the necessary currency exchange rate information. See the model for the exact specifications.
    pub request_body: std::collections::HashMap<String, String>,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::update_currency_exchange_rate`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateCurrencyExchangeRateParams {
    /// The ID of the currency exchange rate.
    pub id: String,
    /// JSON array or form-data with updated exchange rate information. See the model for the exact specifications.
    pub currency_exchange_rate_update: models::CurrencyExchangeRateUpdate,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`CurrencyExchangeRatesApi::update_currency_exchange_rate_by_date`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateCurrencyExchangeRateByDateParams {
    /// The currency code of the 'from' currency.
    pub from: String,
    /// The currency code of the 'to' currency.
    pub to: String,
    pub date: String,
    /// JSON array or form-data with updated exchange rate information. See the model for the exact specifications.
    pub currency_exchange_rate_update_no_date: models::CurrencyExchangeRateUpdateNoDate,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

#[async_trait]
impl CurrencyExchangeRatesApi for CurrencyExchangeRatesApiClient {
    /// Delete a specific currency exchange rate by its internal ID.
    async fn delete_specific_currency_exchange_rate(
        &self,
        params: DeleteSpecificCurrencyExchangeRateParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRateError>> {
        let DeleteSpecificCurrencyExchangeRateParams { id, x_trace_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteSpecificCurrencyExchangeRateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Delete the currency exchange rate from 'from' to 'to' on the specified date.  It's important to know that the reverse exchange rate (from 'to' to 'from') will not be deleted and Firefly III will still be able to infer the correct exchange rate from the reverse one.
    async fn delete_specific_currency_exchange_rate_on_date(
        &self,
        params: DeleteSpecificCurrencyExchangeRateOnDateParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRateOnDateError>> {
        let DeleteSpecificCurrencyExchangeRateOnDateParams {
            from,
            to,
            date,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{from}/{to}/{date}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to),
            date = crate::apis::urlencode(date)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteSpecificCurrencyExchangeRateOnDateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Deletes ALL currency exchange rates from 'from' to 'to'. It's important to know that the reverse exchange rates (from 'to' to 'from') will not be deleted and Firefly III will still be able to infer the correct exchange rate from the reverse one.
    async fn delete_specific_currency_exchange_rates(
        &self,
        params: DeleteSpecificCurrencyExchangeRatesParams,
    ) -> Result<(), Error<DeleteSpecificCurrencyExchangeRatesError>> {
        let DeleteSpecificCurrencyExchangeRatesParams {
            from,
            to,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{from}/{to}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteSpecificCurrencyExchangeRatesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List exchange rates that Firefly III knows.
    async fn list_currency_exchange_rates(
        &self,
        params: ListCurrencyExchangeRatesParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListCurrencyExchangeRatesError>> {
        let ListCurrencyExchangeRatesParams {
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/exchange-rates", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListCurrencyExchangeRatesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List a single specific exchange rate by its ID.
    async fn list_specific_currency_exchange_rate(
        &self,
        params: ListSpecificCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<ListSpecificCurrencyExchangeRateError>>
    {
        let ListSpecificCurrencyExchangeRateParams {
            id,
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListSpecificCurrencyExchangeRateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List the exchange rate for the from and to-currency on the requested date.
    async fn list_specific_currency_exchange_rate_on_date(
        &self,
        params: ListSpecificCurrencyExchangeRateOnDateParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListSpecificCurrencyExchangeRateOnDateError>>
    {
        let ListSpecificCurrencyExchangeRateOnDateParams {
            from,
            to,
            date,
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{from}/{to}/{date}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to),
            date = crate::apis::urlencode(date)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListSpecificCurrencyExchangeRateOnDateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List all exchange rates from/to the mentioned currencies.
    async fn list_specific_currency_exchange_rates(
        &self,
        params: ListSpecificCurrencyExchangeRatesParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<ListSpecificCurrencyExchangeRatesError>>
    {
        let ListSpecificCurrencyExchangeRatesParams {
            from,
            to,
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{from}/{to}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListSpecificCurrencyExchangeRatesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Stores a new exchange rate. The data required can be submitted as a JSON body or as a list of parameters.
    async fn store_currency_exchange_rate(
        &self,
        params: StoreCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<StoreCurrencyExchangeRateError>> {
        let StoreCurrencyExchangeRateParams {
            currency_exchange_rate_store,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/exchange-rates", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&currency_exchange_rate_store);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<StoreCurrencyExchangeRateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Stores a new set of exchange rates. The date is fixed (in the URL parameter) and the data required can be submitted as a JSON body.
    async fn store_currency_exchange_rates_by_date(
        &self,
        params: StoreCurrencyExchangeRatesByDateParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<StoreCurrencyExchangeRatesByDateError>>
    {
        let StoreCurrencyExchangeRatesByDateParams {
            date,
            currency_exchange_rate_store_by_date,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/by-date/{date}",
            local_var_configuration.base_path,
            date = crate::apis::urlencode(date)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&currency_exchange_rate_store_by_date);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<StoreCurrencyExchangeRatesByDateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Stores a new set of exchange rates for this pair. The date is variable, and the data required can be submitted as a JSON body.
    async fn store_currency_exchange_rates_by_pair(
        &self,
        params: StoreCurrencyExchangeRatesByPairParams,
    ) -> Result<models::CurrencyExchangeRateArray, Error<StoreCurrencyExchangeRatesByPairError>>
    {
        let StoreCurrencyExchangeRatesByPairParams {
            from,
            to,
            request_body,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/by-currencies/{from}/{to}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&request_body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<StoreCurrencyExchangeRatesByPairError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Used to update a single currency exchange rate by its ID. Including the from/to currency is optional.
    async fn update_currency_exchange_rate(
        &self,
        params: UpdateCurrencyExchangeRateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<UpdateCurrencyExchangeRateError>> {
        let UpdateCurrencyExchangeRateParams {
            id,
            currency_exchange_rate_update,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&currency_exchange_rate_update);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateCurrencyExchangeRateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Used to update a single currency exchange rate by its currency codes and date
    async fn update_currency_exchange_rate_by_date(
        &self,
        params: UpdateCurrencyExchangeRateByDateParams,
    ) -> Result<models::CurrencyExchangeRateSingle, Error<UpdateCurrencyExchangeRateByDateError>>
    {
        let UpdateCurrencyExchangeRateByDateParams {
            from,
            to,
            date,
            currency_exchange_rate_update_no_date,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/exchange-rates/{from}/{to}/{date}",
            local_var_configuration.base_path,
            from = crate::apis::urlencode(from),
            to = crate::apis::urlencode(to),
            date = crate::apis::urlencode(date)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&currency_exchange_rate_update_no_date);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CurrencyExchangeRateSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateCurrencyExchangeRateByDateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSpecificCurrencyExchangeRateError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rate_on_date`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSpecificCurrencyExchangeRateOnDateError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::delete_specific_currency_exchange_rates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSpecificCurrencyExchangeRatesError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::list_currency_exchange_rates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCurrencyExchangeRatesError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSpecificCurrencyExchangeRateError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rate_on_date`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSpecificCurrencyExchangeRateOnDateError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::list_specific_currency_exchange_rates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSpecificCurrencyExchangeRatesError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::store_currency_exchange_rate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreCurrencyExchangeRateError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::store_currency_exchange_rates_by_date`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreCurrencyExchangeRatesByDateError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::store_currency_exchange_rates_by_pair`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreCurrencyExchangeRatesByPairError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::update_currency_exchange_rate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCurrencyExchangeRateError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CurrencyExchangeRatesApi::update_currency_exchange_rate_by_date`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCurrencyExchangeRateByDateError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    UnknownValue(serde_json::Value),
}
