/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait SummaryApi: Send + Sync {
    /// GET /v1/summary/basic
    ///
    /// Returns basic sums of the users data, like the net worth, spent and earned amounts. It is multi-currency, and is used in Firefly III to populate the dashboard.
    async fn get_basic_summary(
        &self,
        params: GetBasicSummaryParams,
    ) -> Result<
        std::collections::HashMap<String, models::BasicSummaryEntry>,
        Error<GetBasicSummaryError>,
    >;
}

pub struct SummaryApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl SummaryApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`SummaryApi::get_basic_summary`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetBasicSummaryParams {
    /// A date formatted YYYY-MM-DD.
    pub start: String,
    /// A date formatted YYYY-MM-DD.
    pub end: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// A currency code like EUR or USD, to filter the result.
    pub currency_code: Option<String>,
}

#[async_trait]
impl SummaryApi for SummaryApiClient {
    /// Returns basic sums of the users data, like the net worth, spent and earned amounts. It is multi-currency, and is used in Firefly III to populate the dashboard.
    async fn get_basic_summary(
        &self,
        params: GetBasicSummaryParams,
    ) -> Result<
        std::collections::HashMap<String, models::BasicSummaryEntry>,
        Error<GetBasicSummaryError>,
    > {
        let GetBasicSummaryParams {
            start,
            end,
            x_trace_id,
            currency_code,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/summary/basic", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("start", &start.to_string())]);
        local_var_req_builder = local_var_req_builder.query(&[("end", &end.to_string())]);
        if let Some(ref param_value) = currency_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("currency_code", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::BasicSummaryEntry&gt;`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::BasicSummaryEntry&gt;`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetBasicSummaryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`SummaryApi::get_basic_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBasicSummaryError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}
