/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait TagsApi: Send + Sync {
    /// DELETE /v1/tags/{tag}
    ///
    /// Delete an tag.
    async fn delete_tag(&self, params: DeleteTagParams) -> Result<(), Error<DeleteTagError>>;

    /// GET /v1/tags/{tag}
    ///
    /// Get a single tag.
    async fn get_tag(&self, params: GetTagParams) -> Result<models::TagSingle, Error<GetTagError>>;

    /// GET /v1/tags/{tag}/attachments
    ///
    /// Lists all attachments.
    async fn list_attachment_by_tag(
        &self,
        params: ListAttachmentByTagParams,
    ) -> Result<models::AttachmentArray, Error<ListAttachmentByTagError>>;

    /// GET /v1/tags
    ///
    /// List all of the user's tags.
    async fn list_tag(
        &self,
        params: ListTagParams,
    ) -> Result<models::TagArray, Error<ListTagError>>;

    /// GET /v1/tags/{tag}/transactions
    ///
    /// List all transactions with this tag.
    async fn list_transaction_by_tag(
        &self,
        params: ListTransactionByTagParams,
    ) -> Result<models::TransactionArray, Error<ListTransactionByTagError>>;

    /// POST /v1/tags
    ///
    /// Creates a new tag. The data required can be submitted as a JSON body or as a list of parameters.
    async fn store_tag(
        &self,
        params: StoreTagParams,
    ) -> Result<models::TagSingle, Error<StoreTagError>>;

    /// PUT /v1/tags/{tag}
    ///
    /// Update existing tag.
    async fn update_tag(
        &self,
        params: UpdateTagParams,
    ) -> Result<models::TagSingle, Error<UpdateTagError>>;
}

pub struct TagsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl TagsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`TagsApi::delete_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteTagParams {
    /// Either the tag itself or the tag ID. If you use the tag itself, and it contains international (non-ASCII) characters, your mileage may vary.
    pub tag: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`TagsApi::get_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetTagParams {
    /// Either the tag itself or the tag ID. If you use the tag itself, and it contains international (non-ASCII) characters, your mileage may vary.
    pub tag: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`TagsApi::list_attachment_by_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListAttachmentByTagParams {
    /// Either the tag itself or the tag ID.
    pub tag: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`TagsApi::list_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListTagParams {
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
}

/// struct for passing parameters to the method [`TagsApi::list_transaction_by_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListTransactionByTagParams {
    /// Either the tag itself or the tag ID.
    pub tag: String,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
    /// Number of items per page. The default pagination is per 50 items.
    pub limit: Option<i32>,
    /// Page number. The default pagination is per 50 items.
    pub page: Option<i32>,
    /// A date formatted YYYY-MM-DD. This is the start date of the selected range (inclusive).
    pub start: Option<String>,
    /// A date formatted YYYY-MM-DD. This is the end date of the selected range (inclusive).
    pub end: Option<String>,
    /// Optional filter on the transaction type(s) returned.
    pub r#type: Option<models::TransactionTypeFilter>,
}

/// struct for passing parameters to the method [`TagsApi::store_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct StoreTagParams {
    /// JSON array or key=value pairs with the necessary tag information. See the model for the exact specifications.
    pub tag_model_store: models::TagModelStore,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

/// struct for passing parameters to the method [`TagsApi::update_tag`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateTagParams {
    /// Either the tag itself or the tag ID. If you use the tag itself, and it contains international (non-ASCII) characters, your mileage may vary.
    pub tag: String,
    /// JSON array with updated tag information. See the model for the exact specifications.
    pub tag_model_update: models::TagModelUpdate,
    /// Unique identifier associated with this request.
    pub x_trace_id: Option<String>,
}

#[async_trait]
impl TagsApi for TagsApiClient {
    /// Delete an tag.
    async fn delete_tag(&self, params: DeleteTagParams) -> Result<(), Error<DeleteTagError>> {
        let DeleteTagParams { tag, x_trace_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/tags/{tag}",
            local_var_configuration.base_path,
            tag = crate::apis::urlencode(tag)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Get a single tag.
    async fn get_tag(&self, params: GetTagParams) -> Result<models::TagSingle, Error<GetTagError>> {
        let GetTagParams {
            tag,
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/tags/{tag}",
            local_var_configuration.base_path,
            tag = crate::apis::urlencode(tag)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::TagSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::TagSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Lists all attachments.
    async fn list_attachment_by_tag(
        &self,
        params: ListAttachmentByTagParams,
    ) -> Result<models::AttachmentArray, Error<ListAttachmentByTagError>> {
        let ListAttachmentByTagParams {
            tag,
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/tags/{tag}/attachments",
            local_var_configuration.base_path,
            tag = crate::apis::urlencode(tag)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AttachmentArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AttachmentArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListAttachmentByTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List all of the user's tags.
    async fn list_tag(
        &self,
        params: ListTagParams,
    ) -> Result<models::TagArray, Error<ListTagError>> {
        let ListTagParams {
            x_trace_id,
            limit,
            page,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/tags", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::TagArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::TagArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// List all transactions with this tag.
    async fn list_transaction_by_tag(
        &self,
        params: ListTransactionByTagParams,
    ) -> Result<models::TransactionArray, Error<ListTransactionByTagError>> {
        let ListTransactionByTagParams {
            tag,
            x_trace_id,
            limit,
            page,
            start,
            end,
            r#type,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/tags/{tag}/transactions",
            local_var_configuration.base_path,
            tag = crate::apis::urlencode(tag)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start {
            local_var_req_builder =
                local_var_req_builder.query(&[("start", &param_value.to_string())]);
        }
        if let Some(ref param_value) = end {
            local_var_req_builder =
                local_var_req_builder.query(&[("end", &param_value.to_string())]);
        }
        if let Some(ref param_value) = r#type {
            local_var_req_builder =
                local_var_req_builder.query(&[("type", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::TransactionArray`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::TransactionArray`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ListTransactionByTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Creates a new tag. The data required can be submitted as a JSON body or as a list of parameters.
    async fn store_tag(
        &self,
        params: StoreTagParams,
    ) -> Result<models::TagSingle, Error<StoreTagError>> {
        let StoreTagParams {
            tag_model_store,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/tags", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&tag_model_store);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::TagSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::TagSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<StoreTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Update existing tag.
    async fn update_tag(
        &self,
        params: UpdateTagParams,
    ) -> Result<models::TagSingle, Error<UpdateTagError>> {
        let UpdateTagParams {
            tag,
            tag_model_update,
            x_trace_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/v1/tags/{tag}",
            local_var_configuration.base_path,
            tag = crate::apis::urlencode(tag)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_trace_id {
            local_var_req_builder =
                local_var_req_builder.header("X-Trace-Id", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&tag_model_update);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::TagSingle`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::TagSingle`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateTagError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`TagsApi::delete_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTagError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::get_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTagError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::list_attachment_by_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAttachmentByTagError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::list_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTagError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::list_transaction_by_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTransactionByTagError {
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::store_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreTagError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TagsApi::update_tag`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTagError {
    Status422(models::ValidationErrorResponse),
    Status401(models::UnauthenticatedResponse),
    Status404(models::NotFoundResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalExceptionResponse),
    UnknownValue(serde_json::Value),
}
