/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutocompleteTransaction {
    /// The ID of a transaction journal (basically a single split).
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the underlying transaction group.
    #[serde(
        rename = "transaction_group_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub transaction_group_id: Option<String>,
    /// Transaction description
    #[serde(rename = "name")]
    pub name: String,
    /// Transaction description
    #[serde(rename = "description")]
    pub description: String,
}

impl AutocompleteTransaction {
    pub fn new(id: String, name: String, description: String) -> AutocompleteTransaction {
        AutocompleteTransaction {
            id,
            transaction_group_id: None,
            name,
            description,
        }
    }
}
