/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ConfigValueUpdateFilter {
    #[serde(rename = "configuration.is_demo_site")]
    #[default]
    ConfigurationIsDemoSite,
    #[serde(rename = "configuration.permission_update_check")]
    ConfigurationPermissionUpdateCheck,
    #[serde(rename = "configuration.last_update_check")]
    ConfigurationLastUpdateCheck,
    #[serde(rename = "configuration.single_user_mode")]
    ConfigurationSingleUserMode,
    #[serde(rename = "configuration.enable_exchange_rates")]
    ConfigurationEnableExchangeRates,
    #[serde(rename = "configuration.use_running_balance")]
    ConfigurationUseRunningBalance,
    #[serde(rename = "configuration.enable_external_map")]
    ConfigurationEnableExternalMap,
    #[serde(rename = "configuration.enable_external_rates")]
    ConfigurationEnableExternalRates,
    #[serde(rename = "configuration.allow_webhooks")]
    ConfigurationAllowWebhooks,
    #[serde(rename = "configuration.valid_url_protocols")]
    ConfigurationValidUrlProtocols,
}

impl std::fmt::Display for ConfigValueUpdateFilter {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ConfigurationIsDemoSite => write!(f, "configuration.is_demo_site"),
            Self::ConfigurationPermissionUpdateCheck => {
                write!(f, "configuration.permission_update_check")
            }
            Self::ConfigurationLastUpdateCheck => write!(f, "configuration.last_update_check"),
            Self::ConfigurationSingleUserMode => write!(f, "configuration.single_user_mode"),
            Self::ConfigurationEnableExchangeRates => {
                write!(f, "configuration.enable_exchange_rates")
            }
            Self::ConfigurationUseRunningBalance => write!(f, "configuration.use_running_balance"),
            Self::ConfigurationEnableExternalMap => write!(f, "configuration.enable_external_map"),
            Self::ConfigurationEnableExternalRates => {
                write!(f, "configuration.enable_external_rates")
            }
            Self::ConfigurationAllowWebhooks => write!(f, "configuration.allow_webhooks"),
            Self::ConfigurationValidUrlProtocols => write!(f, "configuration.valid_url_protocols"),
        }
    }
}
