/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum DataDestroyObject {
    #[serde(rename = "not_assets_liabilities")]
    #[default]
    NotAssetsLiabilities,
    #[serde(rename = "budgets")]
    Budgets,
    #[serde(rename = "bills")]
    Bills,
    #[serde(rename = "piggy_banks")]
    PiggyBanks,
    #[serde(rename = "rules")]
    Rules,
    #[serde(rename = "recurring")]
    Recurring,
    #[serde(rename = "categories")]
    Categories,
    #[serde(rename = "tags")]
    Tags,
    #[serde(rename = "object_groups")]
    ObjectGroups,
    #[serde(rename = "accounts")]
    Accounts,
    #[serde(rename = "asset_accounts")]
    AssetAccounts,
    #[serde(rename = "expense_accounts")]
    ExpenseAccounts,
    #[serde(rename = "revenue_accounts")]
    RevenueAccounts,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "withdrawals")]
    Withdrawals,
    #[serde(rename = "deposits")]
    Deposits,
    #[serde(rename = "transfers")]
    Transfers,
}

impl std::fmt::Display for DataDestroyObject {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotAssetsLiabilities => write!(f, "not_assets_liabilities"),
            Self::Budgets => write!(f, "budgets"),
            Self::Bills => write!(f, "bills"),
            Self::PiggyBanks => write!(f, "piggy_banks"),
            Self::Rules => write!(f, "rules"),
            Self::Recurring => write!(f, "recurring"),
            Self::Categories => write!(f, "categories"),
            Self::Tags => write!(f, "tags"),
            Self::ObjectGroups => write!(f, "object_groups"),
            Self::Accounts => write!(f, "accounts"),
            Self::AssetAccounts => write!(f, "asset_accounts"),
            Self::ExpenseAccounts => write!(f, "expense_accounts"),
            Self::RevenueAccounts => write!(f, "revenue_accounts"),
            Self::Liabilities => write!(f, "liabilities"),
            Self::Transactions => write!(f, "transactions"),
            Self::Withdrawals => write!(f, "withdrawals"),
            Self::Deposits => write!(f, "deposits"),
            Self::Transfers => write!(f, "transfers"),
        }
    }
}
