/*
 * Firefly III API v6.5.5
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small>
 *
 * The version of the OpenAPI document: v6.5.5
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiabilityTypeProperty : Mandatory when type is liability. Specifies the exact type.
/// Mandatory when type is liability. Specifies the exact type.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum LiabilityTypeProperty {
    #[serde(rename = "loan")]
    #[default]
    Loan,
    #[serde(rename = "debt")]
    Debt,
    #[serde(rename = "mortgage")]
    Mortgage,
}

impl std::fmt::Display for LiabilityTypeProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Loan => write!(f, "loan"),
            Self::Debt => write!(f, "debt"),
            Self::Mortgage => write!(f, "mortgage"),
        }
    }
}
